### ISSUE TITLE
Uncaught ReferenceError: StartNewKeypair is not defined

### ISSUE THREAD

**Issue by nicola** [linkeddata/webid-keychain#1]
I use my webID (which has already a key),
I click on `New Key`, and I obtain the following on line 22:

```
Uncaught ReferenceError: StartNewKeypair is not defined
```

(although this might not be implemented yet, I thought it will be great to have this issue as reference)

**Comment by deiu** [comment]
Yeah, this code is not ready for public use, but I didn't want to make the repo private though. I'll add a disclaimer to let people know not to play with it.

**Comment by nicola** [comment]
:boom:
